// GENERATED by setup.dart from core/go.mod — do not edit by hand
// ignore_for_file: constant_identifier_names

/// Embedded mihomo base version; lifecycle patch is in core/tools/mihomo-overlay.
const String kCoreVersionFromSource = 'v1.19.32';
